import type { TrendItem } from "../types"

export const trendOverview: TrendItem[] = [
  {
    id: "t1",
    title: "AI Workflow Mapping",
    category: "Workflow Automation",
    demandSignal: "high",
    growthIndicator: "+34%",
    relatedRequests: 42,
    trendDirection: "up",
    percentChange: 34,
  },
  {
    id: "t2",
    title: "CRM Repair & Migration",
    category: "CRM Setup",
    demandSignal: "high",
    growthIndicator: "+22%",
    relatedRequests: 31,
    trendDirection: "up",
    percentChange: 22,
  },
  {
    id: "t3",
    title: "Proposal Automation",
    category: "Software Development",
    demandSignal: "medium",
    growthIndicator: "+18%",
    relatedRequests: 19,
    trendDirection: "up",
    percentChange: 18,
  },
  {
    id: "t4",
    title: "Real Estate Follow-up Systems",
    category: "Real Estate Ops",
    demandSignal: "high",
    growthIndicator: "+28%",
    relatedRequests: 27,
    trendDirection: "up",
    percentChange: 28,
  },
]

export const newSkills: TrendItem[] = [
  {
    id: "ns1",
    title: "AI Workflow Mapping",
    category: "Workflow Automation",
    demandSignal: "high",
    growthIndicator: "+34%",
    relatedRequests: 42,
  },
  {
    id: "ns2",
    title: "CRM Repair",
    category: "CRM Setup",
    demandSignal: "high",
    growthIndicator: "+22%",
    relatedRequests: 31,
  },
  {
    id: "ns3",
    title: "Proposal Automation",
    category: "Software Development",
    demandSignal: "medium",
    growthIndicator: "+18%",
    relatedRequests: 19,
  },
  {
    id: "ns4",
    title: "Multi-channel Support Ops",
    category: "Voice Support",
    demandSignal: "medium",
    growthIndicator: "+14%",
    relatedRequests: 16,
  },
  {
    id: "ns5",
    title: "Real Estate Follow-up Systems",
    category: "Real Estate Ops",
    demandSignal: "high",
    growthIndicator: "+28%",
    relatedRequests: 27,
  },
  {
    id: "ns6",
    title: "Contractor Onboarding Automation",
    category: "Contractor Coordination",
    demandSignal: "medium",
    growthIndicator: "+12%",
    relatedRequests: 11,
  },
]

export const updatedSkills: TrendItem[] = [
  {
    id: "us1",
    title: "Salesforce Administration",
    category: "CRM Setup",
    demandSignal: "high",
    growthIndicator: "+14%",
    relatedRequests: 38,
    trendDirection: "up",
    percentChange: 14,
    lastUpdated: "2 days ago",
    relatedCategories: ["CRM Setup", "Sales Ops"],
  },
  {
    id: "us2",
    title: "Email Deliverability",
    category: "Email Operations",
    demandSignal: "medium",
    growthIndicator: "+8%",
    relatedRequests: 22,
    trendDirection: "up",
    percentChange: 8,
    lastUpdated: "3 days ago",
    relatedCategories: ["Email Operations", "Marketing"],
  },
  {
    id: "us3",
    title: "WordPress Maintenance",
    category: "Website Support",
    demandSignal: "low",
    growthIndicator: "-3%",
    relatedRequests: 14,
    trendDirection: "down",
    percentChange: -3,
    lastUpdated: "1 day ago",
    relatedCategories: ["Website Support"],
  },
  {
    id: "us4",
    title: "Cold Calling",
    category: "Appointment Setting",
    demandSignal: "medium",
    growthIndicator: "+6%",
    relatedRequests: 18,
    trendDirection: "up",
    percentChange: 6,
    lastUpdated: "4 days ago",
    relatedCategories: ["Lead Qualification", "Sales Ops"],
  },
  {
    id: "us5",
    title: "Zapier Integrations",
    category: "Workflow Automation",
    demandSignal: "high",
    growthIndicator: "+19%",
    relatedRequests: 33,
    trendDirection: "up",
    percentChange: 19,
    lastUpdated: "1 day ago",
    relatedCategories: ["Workflow Automation", "CRM Setup"],
  },
]

export const marketSignals = [
  { id: "ms1", label: "Emerging Demand", value: "AI Workflow Mapping", detail: "42 new requests this month" },
  { id: "ms2", label: "Most Requested Skills", value: "CRM + Automation", detail: "Combined 73 active requests" },
  { id: "ms3", label: "Fastest Growing Category", value: "Real Estate Ops", detail: "+28% month over month" },
  { id: "ms4", label: "Regional Activity", value: "US Northeast", detail: "Highest volume, 34% of total" },
]
